### ISSUE TITLE
support for .bvh or .fbx export?

### ISSUE THREAD

**Issue by whatthesamuel** [ButzYung/SystemAnimatorOnline#1]
I noticed that the software has an option for importing fbx files but doesn't offer an output feature. Although I understand it was primarily made for VTubers, to better serve other use cases such as game development or film making, I believe it should have built-in support for exporting results to .fbx format.

This is the most impressive webcam to mocap software I've tested thus far. So I really hope you consider adding it.

**Comment by ButzYung** [comment]
XR Animator does have a motion export option. You can export mocap data, FBX and BVH motion to VMD (MMD-based) format (the only format supported in the mean time).

Personally I would like to do an export option for FBX, but the issue is that there is no FBX exporter for `three.js` available mainly due the proprietary format of FBX (a motion-only FBX may be easier to implement I suppose?).

BVH export is definitely do-able, though right now it's not my first priority to do so.

**Comment by whatthesamuel** [comment]
> XR Animator does have a motion export option. You can export mocap data, FBX and BVH motion to VMD (MMD-based) format (the only format supported in the mean time).
>

Yeah, I'm aware of that, but using vmd in game engines other than unity is a real pain. Also as far as I know, vmd has limited uses in other 3d applications too.

> 
> BVH export is definitely do-able, though right now it's not my first priority to do so.

That would be much appreciated. I would have contributed myself if I could, but I don't know how vmd works, so I'll be looking forward to the next update!

**Comment by V0dot0** [comment]
You can definitely export them in fbx, but it is quite a difficult setup.(It's not really optimized way to do it but it works). I used Unreal with VSeeFace but you can use Unity. Basically you open send XR animator VMC-data to VSeeface, then VSeeFace sends data to Unreal. Unreal with special 3 free plugins gets the data. Then you use official Take Recording plugin in Unreal to record the animation. (Guide on VSeeFace to Unreal Engine search Youtube for "Unreal Engine Vtuber set up and walkthrough"-by Fofamit. Then you probably need to change ports to match, then learn about Unreal's Take Recorder. ) Hope it help.

**Comment by whatthesamuel** [comment]
I know exporting vmd to UE is a thing, but I opened this issue as a feature request since, as you mentioned, it's a quite a pain to do so. The project creator mentioned that he might be able to implement bvh, so I'll close this issue when it gets done.
