### ISSUE TITLE
Avatar's hair problem

### ISSUE THREAD

**Issue by NekoChan-Npc** [ButzYung/SystemAnimatorOnline#100]
I use the vroid to create my avatar, but my long hair never seems to flow, can someone help to solve the problem, thankyou

**Comment by ButzYung** [comment]
Does your model's hair work on other apps? Or is it just a problem on XR Animator?

**Comment by NekoChan-Npc** [comment]
Thank you for your reply and wish you a Merry Christmas
Positive, i have tried the other apps and my model is working well. The hair looked flowing smoothly and gently when i move my head in other apps. So i think it is an issue in XR.

**Comment by NekoChan-Npc** [comment]
Wow, i m quite surprise when you email to me.My model's hair was working well on other apps, but my model's hair feels hard like a metal when i load it into XR. 
    On Wednesday, December 25, 2024 at 03:54:10 AM GMT+8, ButzYung ***@***.***> wrote:  
 
 


Does your model's hair work on other apps? Or is it just a problem on XR Animator?

**Comment by ButzYung** [comment]
Stiff springbone physics on some models is a known issue, and has been fixed in the early-access version for members. This fix will be available on GitHub eventually, but in the mean time you can go to "UI/Options➡️Miscellaneous options➡️VRM joint stiffness" option and lower the value.

**Comment by NekoChan-Npc** [comment]
Thank for your help, i had fixed the issue :3
