### ISSUE TITLE
Feature Request: Linux/Mac builds or build instructions

### ISSUE THREAD

**Issue by jurassicjordan** [ButzYung/SystemAnimatorOnline#12]
Being that platforms like the steamdeck and new M2 macbooks are growing in popularity, it would be fantastic to have the project available on these systems as a desktop tool. I kindly request to consider providing Linux and Mac builds or at least including build instructions specifically tailored for these platforms, since electron is a cross-platform toolkit. This would make it much easier for users like me to get started and contribute to the project. Thanks a lot for your attention, and I'm looking forward to seeing XR Animator become even more accessible and inclusive!

**Comment by ButzYung** [comment]
@jurassicjordan A few years ago, back in the days when XR Animator was still in its predecessor form as a desktop gadget, it actually had a Linux version...

https://www.youtube.com/watch?v=SVWF3Zq1F7A

Now that you mentioned it, I install the Linux VM again, put the latest version of XR Animator on it, and guess what, IT STILL WORKS LOL. There are some minor issues, but all major features of XR Animator work, including webcam mocap. I think I will include Linux build in the future, but in the mean time, you are very welcomed to try the following steps and test it.

1. [Download the Windows version of XR Animator.](https://github.com/ButzYung/SystemAnimatorOnline/releases)
2. [Download the official build of electron for Linux.](https://github.com/electron/electron/releases/tag/v22.3.14) Version 22.x is recommended as this is what the current version of XR Animator uses.
3. Unzip them both.
4. Go to the XR Animator folder, and under the `resources` folder of Windows electron, copy the following files.
- app.asar
- icon_SA_512x512.png
- icon_teto_512x512.png
5. Go to the Linux electron folder, and paste these files into the `resources` folder.
6. Put the Linux electron folder under XR Animator folder.
7. Launch Linux electron.

Feel free to report any issues you discover.

As for Mac version, I don't have a Mac computer so unfortunately it would be very difficult for me to port it in the mean time.

**Comment by jurassicjordan** [comment]
oh thank you very much for your consideration and the build info! And I totally understand the limitations with mac. even I don't have a modern one, but just supporting Linux is even more inclusive than just supporting mac and windows.
