### ISSUE TITLE
No more wireframe display?

### ISSUE THREAD

**Issue by MioBlackHeart** [ButzYung/SystemAnimatorOnline#24]
Thanks for the Version 13 update. Tho I notice wireframe display been remove with some other things. I did find the wireframe display useful. Any plan to have it return?

**Comment by ButzYung** [comment]
> Thanks for the Version 13 update. Tho I notice wireframe display been remove with some other things. I did find the wireframe display useful. Any plan to have it return?

The wireframe feature is still there. Make sure you didn't accidentally disable it. You can check at UI/Options => Overlay & UI

**Comment by MioBlackHeart** [comment]
I re download the files. weird enough its there now. before it wasn't even listed.
