### ISSUE TITLE
Can't use Ctrl+Z when XR-Animator is running.

### ISSUE THREAD

**Issue by Bco1981** [ButzYung/SystemAnimatorOnline#34]
I load XR-Animator on Windows, initial test v0.13.0, just tested latest 0.15.1 same issue.
load a mmd model, have it running.

While working in any app that supports undo, can't use Ctrl+Z, it has no effect.
Closing XR-Animator and Ctrl+Z works again.

**Comment by ButzYung** [comment]
Fixed in the latest v0.15.2. The default hotkey of "arm-as-leg" control has been changed from Ctrl+Z to Shift+Z. You can always configure each hotkey separately, but this saves you the efforts from having to do so.
