### ISSUE TITLE
Bug, converting to VMD and importing in blender, no leg movement

### ISSUE THREAD

**Issue by SkylarMark** [ButzYung/SystemAnimatorOnline#38]
I have been trying to import an animation from a FBX file to my mmd character in blender, but after converting the animation from XR Animator. Somehow the leg movements are not mapped to the proper bone i think

**Comment by ButzYung** [comment]
Do you mean dropping the FBX animation to XR Animator, converting it to VMD, applying it on Blender but the leg movements don't work?

**Comment by SkylarMark** [comment]
yes exactly

**Comment by ButzYung** [comment]
How about if you drop the converted VMD back to XR Animator, or use it on MikuMikuDance, does it work that way?

Note that VMD converted this way does not have leg IK motions.

**Comment by SkylarMark** [comment]
`How about if you drop the converted VMD back to XR Animator, or use it on MikuMikuDance, does it work that way?`
its working perfectly fine

I guess i just had to remove the IK before importing the VMD motion file

@ButzYung  Thank you for lending me a helping hand. I truly appreciate your kindness and assistance.

![image](https://github.com/ButzYung/SystemAnimatorOnline/assets/58359732/aa329d19-18c2-4fa8-a808-0f345d66b09c)
