### ISSUE TITLE
vmd incorrect motion in mmd

### ISSUE THREAD

**Issue by NaveenSohal** [ButzYung/SystemAnimatorOnline#52]
I don't know if this is the right place but here is the issue:
vmd file exported from XR animator losses 70% of its motion and character feet goes below ground axis. Legs movement don't work at all and jumping and moving makes it worse. All in all in XR animator it looks like profession dancer same when exported to vmd and used in mmd looks like a rookie trying to imitate and having very stiff movements.

I'm using genshin impact model PMX file Which i suppose is in chinese.

**Comment by maxellabdullah** [comment]
> What do you mean by losing 70% of its motion?
> 
> Feet grounding is a known issue, as this is a technical limitation of this kind of purely video-based mocap. You can enable the "auto grounding" option to always ground the feet, at the expense of losing the ability to jump.
> 
> Also note that exported VMD motion has no leg IK motion by default. If you use it on MMD you will have to disable the leg IKs or the leg motions will look weird. Enable leg IK option on XR Animator if you want to export VMD with leg IK motions.
> 
> Grounding the character properly, disabling ground shadow and using some camera works can make exported animations look better.

Hello. where is the option to enable leg ik in xr animation?

**Comment by NaveenSohal** [comment]
> What do you mean by losing 70% of its motion?
> 
> Feet grounding is a known issue, as this is a technical limitation of this kind of purely video-based mocap. You can enable the "auto grounding" option to always ground the feet, at the expense of losing the ability to jump.
> 
> Also note that exported VMD motion has no leg IK motion by default. If you use it on MMD you will have to disable the leg IKs or the leg motions will look weird. Enable leg IK option on XR Animator if you want to export VMD with leg IK motions.
> 
> Grounding the character properly, disabling ground shadow and using some camera works can make exported animations look better.

I'm not able to find the IK motion option in XRanimator or MMD. I have attached the issue in video file to give you better idea of the issue.

https://github.com/ButzYung/SystemAnimatorOnline/assets/90239182/402eb58c-ff1b-4f06-ae6f-b9b41e9469f3

I only need leg motion as XRanimator previews. I also found that IK option fixes this issue but the option is nowhere to be found.

**Comment by maxellabdullah** [comment]
> > What do you mean by losing 70% of its motion?
> > Feet grounding is a known issue, as this is a technical limitation of this kind of purely video-based mocap. You can enable the "auto grounding" option to always ground the feet, at the expense of losing the ability to jump.
> > Also note that exported VMD motion has no leg IK motion by default. If you use it on MMD you will have to disable the leg IKs or the leg motions will look weird. Enable leg IK option on XR Animator if you want to export VMD with leg IK motions.
> > Grounding the character properly, disabling ground shadow and using some camera works can make exported animations look better.
> 
> I'm not able to find the IK motion option in XRanimator or MMD. I have attached the issue in video file to give you better idea of the issue.
> 
>  yela.mmd.no.leg.motion.mp4 
> I only need leg motion as XRanimator previews. I also found that IK option fixes this issue but the option is nowhere to be found.

the ik option in mmd is under the load model button
