### ISSUE TITLE
17.5 vs 18 Issue

### ISSUE THREAD

**Issue by MioBlackHeart** [ButzYung/SystemAnimatorOnline#55]
So The tracking seem to be really bad in version 18 compare to 17.5.

Arm tracking would swing back and forth a lot and sometime even go behind your back when in IRL. your arm and hands are in front of you. The program also lag a lot. 17.5 is a lot more stable and accurate with overall tracking. I can demonstrate in discord video call if you like.

Discord @ Fairithm

**Comment by ButzYung** [comment]
Are you using VRM1.0 model? Does the problem persist if you switch to another model (say like the default model)? Assuming you are using the "MediaPipe Tasks Vision" full body tracking, change to "Legacy Holistic" and see if it makes a difference.

**Comment by MioBlackHeart** [comment]
AI Model Quality: Best @ Depth Scale: MAX - Its causing over sensitivity on the tracking to cause my back to overbend also bug. Having it max setting would also cause weird issue with the tracking arm and body. While setting DS: Min would eliminated/ease the tracking sensitivity. However, comparing it to the Normal - N/A  Setting. There's no weird tracking issue at all and the upper body back wouldn't bend at all.
