### ISSUE TITLE
When the app is not in focus, it will slow down. 

### ISSUE THREAD

**Issue by PeterJared** [ButzYung/SystemAnimatorOnline#60]
This means that if we select a different application, such as a game or a video conferencing app, XR Animator will significantly reduce CPU and GPU usage by drastically lowering the frame rate. This is a standard system in Unity designed to avoid using resources in a game when it is not in use.

However, in this application, we often stream animation from XR Animator while using another application, which can be problematic. Is it possible to disable this slowdown, as I believe can be done in both Unity and Unreal, or at least provide an option to choose whether the slowdown occurs or not? I think this app is great.

For me, the ability to use XR Animator simultaneously with other applications is a crucial feature.

Thanks!

**Comment by ButzYung** [comment]
This is a known issue under certain situations. You can either disable Windows "game mode" (which slows down background apps) or open task manager and give XR Animator a higher processing priority.

**Comment by MioBlackHeart** [comment]
I'm having this issue as well... Game mode doesn't seem to fix it and im on a 14900K at 6GHz. only 10% of my CPU is being utilized and the issue is happening.

**Comment by PeterJared** [comment]
From what I can see, the problem becomes evident if another app competes with XR Animator. For example:

- XR Animator alone, selected or not: It runs at a good speed.
- XR Animator with another 3D competing app:
          It runs fine if it is the focus.
          If it is not in focus, performance depends on how demanding the other app is. For example, if you want to use the app for mocap to edit later, set up the second application with the lowest graphical settings possible to avoid competition. Or, once you start to capture, click on XR Animator to get maximum speed. Both workarounds work but they are not comfortable.

What works, but obviously needs extra resources, is to use a second computer to run XR Animator and stream the animation over a local network. This is possible if you add the IP of the computer running the second application. Then, it is perfect and comfortable to use as performance will be stable.

None of the workarounds from the second post work (e.g., game mode, etc.).  At lest in Windows 11. In Unreal, there is an option to keep the app always in focus. No idea about Unity.

**Comment by MioBlackHeart** [comment]
The program in use while XRA is running are vNyan, Games, Discord, and Web Browser. I notice the issue around version 19 of XRA. I should test the older version of XRA. (version 18). As older one didn't have this issue before.

**Comment by PeterJared** [comment]
How can I test the version 18?

**Comment by MioBlackHeart** [comment]
> How can I test the version 18?

Download and see if it does the issue we both are having. I don't have time to test this week.

https://github.com/ButzYung/SystemAnimatorOnline/releases

**Comment by PeterJared** [comment]
Tested. The behaviour seems different.  19 is  faster than 18. 18 does slowdown less when not in focus, but wont become a lot faster either then in focus. Then the result is a average slow behaviour in both case, that I don't like
With 19. when in focus is very smooth and when not in focus slower. But at least I can use both apps with full speed. 19 full speed is very nice when 18 full speed is annoying. Then I prefer behaviour of 19 as I don't think 18 is usable.
I tried also to set priorities to real time, with little difference.

**Comment by MioBlackHeart** [comment]
> Tested. The behaviour seems different. 19 is faster than 18. 18 does slowdown less when not in focus, but wont become a lot faster either then in focus. Then the result is a average slow behaviour in both cases, that I don't like With 19, when in focus is very smooth and when not in focus slower. But at least I can use both apps with full speed. 19 full speed is very nice when 18 full speed is annoying. Then I prefer behaviour of 19 as I don't think 18 is usable. I tried also to set priorities to real time, with little difference.

Yeh. give 17 a shot? Just trying to narrow the slow down issue.

**Comment by PeterJared** [comment]
After testing 17, basically 17 doesn't care if it is on focus or not, it will give you the same performance. The problem is:
17:

- On focus: 12fps
- Not on focus 12fps

19 and above:

- On focus: 22fps
- Not on focus: 6fps (unless nothing is competing with the XR animator for the GPU)

As you can see 17 is more stable but you can get in certain circunstancies a lot more performance in 19. 
22 fps is very nice and look nearly high quality capture, 12 feel cheap and sluggish , 6 is unusable.

Then, if you want stability, you need to accept a uniform cheap performance. If you want quality, you will be worry continuously who is on focus. The only workaround to that is to use a second computer in a local network to stream XR to the main PC. it works perfect but then you need 2 computers.

**Comment by ButzYung** [comment]
You can try moving the electron folder of v0.17.x to the latest version (v0.19.x), run the latest version of XR Animator using the moved version of electron and see if it makes any difference. Note that you will need to copy `app.asar` from the `resources` subfolder of the latest version of electron and replace the one from the older version of electron you want to run.

**Comment by PeterJared** [comment]
Hi, thanks for the hint.
After trying, I yet get the  same behaviour from 19 (that I prefer to 17)
Meaning:
17:
On focus: 12fps
Not on focus 12fps

19 and above:
On focus: 22fps
Not on focus: 6fps (unless nothing is competing with the XR animator for the GPU)

**Comment by ButzYung** [comment]
Are you using a laptop? I suspect that v0.17 is running on your integrated (slower) GPU, while v0.19 is running on your dedicated (faster) GPU. A recent update in v0.19 enforces the use of faster GPU on laptop. This may explain why the performance on v0.17 is unaffected whether it's focus or not, because while integrated GPU is slower, it isn't competing resources with other apps most of the time.

Have you tried opening task manager and give XR Animator a higher processing priority?

**Comment by PeterJared** [comment]
I tested and you are right. I can see in the task manager what GPU each app is using and in 17 is using the integrated card and in 19 is using the main dedicated Nvidia card
Its yet surprising that it can get 12 fps with a integrated card. And the dedicated card only gets 10fps more even is a lot more powerful and struggles when not in focus.
I tried multiple times to use process priorities and did not work, in both XR and the other 3d ap. Also other friends tested it. It makes no difference as if it was designed for priorities for the CPU but not the GPU.
The other app doesn't care if it is on focus or not, even it can be setup to slowdown when not in focus in their options.

**Comment by ButzYung** [comment]
Just curious, how do you read the FPS info? Are you referring those on the upper left of XR Animator?

**Comment by PeterJared** [comment]
Yes, they reflect quite well the real performance, many times is 24fps and I have I 4080 laptop, the equivalent to a 3080 desktop in terms of performance. But even in a 3070 laptop (I guess similar to a 2080 desktop)  runs quite well at nearly the same speed.
In general top body capture is a extremely good quality when conditions are correct.

**Comment by ButzYung** [comment]
There are multiple values of FPS on XR Animator. P-FPS is the one for body mocap. The front value is the actual FPS, which is technically capped at 30 and is usually slightly lower when system load is heavy. The one behind the slash is the processing FPS, which is often higher than the actual FPS. The last FPS value is the 3D display FPS of XR Animator. For your GPU you should expect 60fps all the time (when in focus).

When used alone, the system requirement of XR Animator is actually quite low. Most of my demos were run on just a GTX1650 GPU, and the FPS is pretty maxed most of the time.

**Comment by PeterJared** [comment]
![image](https://github.com/ButzYung/SystemAnimatorOnline/assets/49351356/3d10e3f3-e381-4d43-9d19-8fc95c7026c3)
This is what I get when the app runs alone and with a competing  app and not on focus (on focus will run ok with competing app)
I place more attention to the P and F lines instead the last one as it reflects better the real performance. 
![image](https://github.com/ButzYung/SystemAnimatorOnline/assets/49351356/6aed8357-af65-44ca-a314-be3fb8ce56f6)

**Comment by PeterJared** [comment]
I just noticed, if my integrated laptop graphic card runs at 12fps, how fast will run in my laptop that only has integrate card? Its a faster integrated card as it is the only one in the system, a  Intel Iris Xe Graphics G7.
It runs faster than 20, nearly the same than the desktop one. The laptop with only integrated card  is  a The Samsung Galaxy Book Pro 360 2

**Comment by PeterJared** [comment]
My card is faster than yours, not sure why it runs faster for your , FPS  etc
I will check with other people what speeds they get

**Comment by MioBlackHeart** [comment]
> My card is faster than yours, not sure why it runs faster for you , FPS etc I will check with other people what speeds they get
you do realize I'm on 1920 x 1080 right? if i match your resolution. its goes 2x the speed cap.

but this topic seem to be steering off course. Trying to resolve the issue with the drop in performance when the program isn't in focus after some period of time. bring the application in front again will resolve that issue but that's only a temp fix until it does it again after not being in focus.

**Comment by PeterJared** [comment]
Obviously, the difference in speed is peculiar. This suggests that there are factors beyond computer specs affecting FPS. It could only be due to:
- The settings you're using in the app. I've noticed some settings can slow down the app, though they enhance quality.
- The model of the camera you have. My inexpensive built-in laptop camera gives me higher FPS than a more costly one I purchased specifically for this purpose. However, I'm not sure if these extra FPS translate to better quality. I need to conduct further tests.
Could you share the settings you're using? For instance, through screenshots? Also, could you specify your camera model? This information could help optimize the app's performance. XR Animator can perform exceptionally well with the right settings, and I'm trying to understand which are the best for predictable app usage. It's definitely the best app utilizing MediaPipe, thanks to the additional AI controls that prevent the app from becoming glitchy when it can't see the subject. In terms of speed, it's impressive how it manages to maintain decent FPS, given that MediaPipe can be quite demanding.

**Comment by PeterJared** [comment]
I solved assigning the app to the second graphic card. Being a laptop, is weaker than the main one, but enough to run XR Animator in a Ok stable speed. Certainly a better experience than using old versions of the app or competing the GPU with other apps.

**Comment by Nomis9** [comment]
Disabling hw-accelerated GPU scheduling fixed it for me
![Image](https://github.com/user-attachments/assets/0e590746-adcf-4db1-960a-971dcecdae7d)
