### ISSUE TITLE
Suggestion: Hand tracking height offset

### ISSUE THREAD

**Issue by QuickFastly** [ButzYung/SystemAnimatorOnline#87]
This program is wonderful and I've got it all fine tuned to work as well as possible for my use case, but for this one minor issue, there doesn't seem to be a solution at the moment. The problem is that the hands of the model are too high relative to my hands on camera. For instance, if I put my hand on my chin, the model covers its mouth. If I touch my finger beneath my eye, the model almost touches its eyebrow.

I assume that this is a problem caused by the model, rather than the software, because some models (like mine) don't have accurate proportions, so unusually long arms might be causing this. But whatever the cause is, having an option to artificially lower (or raise) the hands of the model would be great.

**Comment by ButzYung** [comment]
The `Arm horizontal offset` and `Arm vertical offset` options (under the mocap options) should be what you are looking for.

**Comment by QuickFastly** [comment]
`Arm vertical offset` is exactly what I'm looking for, but it isn't there. On the most recent version (on linux) I still only have the horizontal offset option.

**Comment by QuickFastly** [comment]
Just got the chance to test out the new update, and the vertical offset option works perfectly. Thank you!
