### ISSUE TITLE
Improving beat detection for incoming system audio / live input

### ISSUE THREAD

**Issue by GBaige** [ButzYung/SystemAnimatorOnline#9]
Beat detection has never been accurate on my end. No matter what the monitor sensitivity is, what the gain is, whether the time interval is set to 0.1 seconds, whether beat detection is set to beats only, mixed, or frequencies only; the animation will almost never play to the beat of incoming audio. Sometimes it looks like it plays to the beat, then freezes for a couple of seconds then plays off beat. Even when I play sections of a song that only contain, say, a kick drum, the animation will eventually play off beat.

There must be a way of improving beat detection, or make it so that instead of trying to detect every other beat based on volume peaks (like I suspect it currently does), it should sample a couple of seconds of incoming audio, detect the BPM, and play the animation to the detected BPM instead. Or there could be a way of manually setting the BPM, and playing the animation to that BPM every time audio is detected (independent of the incoming audio's BPM).

**Comment by GBaige** [comment]
I suppose there is no way of improving beat detection for system audio, judging by the lack of replies. I've tried everything, but I give up.

**Comment by ButzYung** [comment]
Sorry for the late reply as I was never notified with this new issue (until you closed it). Depending on how you use the beat detection feature, the actual experience may vary. As a way to enhance music visualization I think it works fairly well. I wonder what you are using it for?

Also note that detecting beats from a local audio file and from a live audio source are based on 2 different algorithms. In general detecting beats from a local audio is more reliable as it actually analyzes the whole file to get the BPM.

**Comment by GBaige** [comment]
Hello! My use of the beat detection feature is rather unorthodox to be honest.

Have you ever heard of a DAW called FL Studio? It has a plugin called Fruity Dance, where an anime girl dances to the BPM of the music/project. There is no actual beat detection involved with Fruity Dance, since it can work even when there;s no audio. It simply takes the BPM that the project is set to, and dances to it.

Now, I don't use FL Studio - I use Renoise - so I've been looking for an alternative. System Animator seemed promising, especially since users can create their own animations, but I understand that there are limitations to detecting the BPM of live input / system audio, so at this point I've very much given up.
